version: "3"

services:
  keyholder:
    container_name: sshcertdemo_keys
    image: sshcertdemo/keys
    build:
      context: '.'
      dockerfile: Dockerfile-keys
    volumes:
     - "keyholder:/data"
  ssh_server:
    container_name: sshcertdemo_server
    image: sshcertdemo/server
    build:
      context: '.'
      dockerfile: Dockerfile-server
    volumes:
      - "keyholder:/data"
  ssh_client:
    container_name: sshcertdemo_client
    image: sshcertdemo/client
    build:
      context: '.'
      dockerfile: Dockerfile-client
    volumes:
      - "keyholder:/data"
    links:
      - "ssh_server"
volumes:
  keyholder:
